name: Compost CI

on:
  push:
    tags: [ "*" ]
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build

      - name: Archive Static Analysis Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: static-analysis-reports
          path: |
            core/build/reports/detekt/*
            ui/build/reports/detekt/*
            demo/build/reports/detekt/*
          retention-days: 5

      - name: Send Telegram Static Analysis
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            Pull Request #${{ github.event.number }}
            [${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/pull/${{event.number}})

            Build failed with Statyc Analysis Result
            failed with following Statyc Analysis result
          document: |
            core/build/reports/detekt/detekt.txt
