name: Compost CI

on:
  push:
    tags: [ "*" ]
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build

      - name: Archive Static Analysis Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports-markdown
          path: |
            core/build/reports/detekt/detekt.md
            ui/build/reports/detekt/detekt.md
