name: Compost CI

on:
  push:
    tags: [ "*" ]
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build

      - name: Unite Statyc Analysis Reports
        if: failure()
        run: |
          echo '# Core Static Analysis' > static-analysis.md
          sed -n '2,10000p' core/build/reports/detekt/detekt.md >> static-analysis.md || echo "Core Static Analysis not found"
          echo '# UI Static Analysis' >> static-analysis.md
          sed -n '2,10000p' ui/build/reports/detekt/detekt.md >> static-analysis.md || echo "UI Static Analysis not found"
          echo '# 'Demo App Static Analysis' >> static-analysis.md
          sed -n '2,10000p' demo/build/reports/detekt/detekt.md >> static-analysis.md || echo "Demo App Static Analysis not found"

      - name: Archive Static Analysis Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: static-analysis-reports
          path: static-analysis.md
          retention-days: 5

      - name: Send Telegram Static Analysis
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            Pull Request *#${{ github.event.pull_request.number }}*
            [${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }})

            *${{ github.event.pull_request.head.ref }}* -> *${{ github.event.pull_request.base.ref }}*

            Build failed with following Statyc Analysis result
          document: static-analysis.md
